# Generated by Django 2.1.2 on 2018-10-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(upload_to='Media')),
                ('Nombre', models.CharField(max_length=100)),
                ('Raza', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.CharField(max_length=9)),
                ('Usuario', models.CharField(max_length=100)),
                ('Clave', models.CharField(max_length=100)),
                ('Rut', models.CharField(max_length=12)),
            ],
        ),
    ]
