# Generated by Django 2.1.2 on 2018-10-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='Estados',
            field=models.CharField(choices=[('A', 'Rescatado'), ('B', 'Disponible'), ('C', 'Adoptado')], default='Rescatado', max_length=10),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='Descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='Raza',
            field=models.CharField(max_length=50),
        ),
    ]
