# Generated by Django 2.1.2 on 2018-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20181030_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='Estados',
        ),
        migrations.AlterField(
            model_name='perrito',
            name='Descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='Raza',
            field=models.CharField(max_length=100),
        ),
    ]
