# Generated by Django 2.1.2 on 2018-11-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20181030_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='Estado',
            field=models.CharField(choices=[('1', 'Rescatado'), ('2', 'Disponible'), ('3', 'Adoptado')], default=1, max_length=10),
        ),
    ]
