# Generated by Django 2.1.2 on 2018-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_perrito_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='Estado',
        ),
        migrations.AddField(
            model_name='perrito',
            name='ESTADOS',
            field=models.CharField(choices=[('1', 'Rescatado'), ('2', 'Disponible'), ('3', 'Adoptado')], default='Rescatado', max_length=11),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='Descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='Raza',
            field=models.CharField(max_length=50),
        ),
    ]
