# Generated by Django 2.1.2 on 2018-11-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20181102_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='Foto',
        ),
    ]
