# Generated by Django 2.1.2 on 2018-11-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_perrito_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='Estado',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='Rescatado', max_length=11),
        ),
    ]
