# Generated by Django 2.1.2 on 2018-11-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20181102_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='Foto',
            field=models.ImageField(default=False, upload_to='Media'),
        ),
    ]
