# Generated by Django 2.1.2 on 2018-11-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20181102_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Media'),
        ),
    ]
