# Generated by Django 2.1.2 on 2018-11-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_auto_20181104_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='Foto',
            field=models.ImageField(default=None, upload_to='Media'),
        ),
    ]
